// @title Zest DSL Playground
// @date 2026-07-19
// @tags fsharp, dsl, features
// @description A tour of the new F# DSL capabilities: inline JS, JSON injection, semantic components, and syntax sugar.
// @layout single

open System
open Zest.Dsl
open Zest.Dsl.DslComponents
open Zest.Dsl.DslSugar

let html =
    divC "post-body" [
        md """
The latest Zest engine upgrade adds inline JavaScript, type-safe JSON data
injection, new semantic components, and a batch of syntax-sugar helpers.
This post is a live demo — every feature below is generated by the F# DSL.

## Inline JavaScript

The `js` helper mirrors `md`: a triple-quoted string wrapped in `<script>`,
with automatic dedent so the body follows F# indentation.
"""

        // ── Inline JS (L2) ──
        divC "demo" [
            buttonC "btn" [ text "Try the inline script" ]
            js """
                document.querySelector('.demo .btn').addEventListener('click', function () {
                    alert('This alert was embedded from F# via the js helper!')
                })
            """
        ]

        md """
## JSON data injection

`jsonBlock` serialises F# data to JSON and injects it as `window.NAME`.
No `sprintf` string concatenation, no XSS risk — `System.Text.Json` handles
all escaping, and `jsSafe` neutralises `</script>`-breaking sequences.
"""

        // ── JSON injection (L3) ──
        jsonBlock "__POST_DATA__" {|
            title = "Zest DSL Playground"
            tags = [|"fsharp"; "dsl"; "features"|]
            wordCount = 250
            published = DateTime.UtcNow.ToString("o")
        |}

        md """
## New components

### Breadcrumb
"""

        // ── Breadcrumb ──
        breadcrumb [("Home", "/"); ("Posts", "/posts/"); ("Playground", "#")]

        md """
### Tag badges
"""

        // ── Tag badges ──
        tagBadges "/tags/" ["fsharp"; "dsl"; "zcss"; "ssg"]

        md """
### Progress bar
"""

        // ── Progress bar ──
        progressBar 80 "Build progress"

        md """
## Syntax sugar

A few of the new text helpers:
"""

        // ── Syntax sugar ──
        ul [
            li [ text ("Pluralize: " + pluralize 3 "feature") ]
            li [ text ("Titleize: " + titleize "my-blog-post") ]
            li [ text ("Capitalize: " + capitalize "hello world") ]
            li [ text ("Truncate: " + truncate_str 20 "This is a longer string that gets cut off") ]
        ]

        md """
## Inline Markdown with dedent

`mdDedent` strips common indentation before rendering, so you can keep
F# source formatting without breaking Markdown headings:
"""

        mdDedent """
            ### Why dedent matters

            Without dedent, an indented `##` heading isn't recognised as a
            heading at all. `mdDedent` fixes this.

            - Bullet lists work
            - **Bold** and *italic* work
            - `inline code` works
        """
    ]

printfn "%s" html
